parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_sqlite'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            currency: Obokaman\StockForecast\Infrastructure\Repository\Doctrine\CustomType\CurrencyCustomType
            stock: Obokaman\StockForecast\Infrastructure\Repository\Doctrine\CustomType\StockCustomType
            subscriber_id: Obokaman\StockForecast\Infrastructure\Repository\Doctrine\CustomType\SubscriberIdCustomType
            chat_id: Obokaman\StockForecast\Infrastructure\Repository\Doctrine\CustomType\ChatIdCustomType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            StockForecast:
                type: yml
                dir: '%kernel.project_dir%/src/StockForecast/Infrastructure/Repository/Doctrine'
                prefix: Obokaman\StockForecast\Domain\Model