index:
    path: /
    defaults: { _controller: 'App\Controller\Home::index' }

telegram_webhook:
    path: /webhook/telegram/{token}/
    defaults: { _controller: 'App\Controller\Telegram\Webhook::index' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
